global:
  scrape_interval:     1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'nestjs'
    static_configs:
      - targets: ['fr-admin-back:3030']
  - job_name: 'statsd_exporter'
    static_configs:
      - targets: [ 'statsd:9102' ]
        labels: { }
    metric_relabel_configs:
      - regex: '(job|instance|url)'
        action: labeldrop
