version: "3.4"
services:

  fr-admin-db:
    image: postgres
    container_name: fr-admin-db
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_BASE}
    volumes:
      - ./postgres/data-dev:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  fr-admin-back:
    container_name: fr-admin-back
    build:
      context: ./nest/
      dockerfile: Dockerfile
      target: development
    volumes: #for hot reloading
      - ./nest/:/usr/src/app
    command: npm run start:dev
    env_file:
      - .env
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_BASE=${DB_BASE}
      - SWAGGER_PREFIX=
    ports:
      - "3030:3030"
    depends_on:
      - fr-admin-db
      - rabbitmq
      - mailer

  fr-admin-front:
    stdin_open: true
    container_name: fr-admin-front
    build:
      context: ./angular/
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./angular:/app/client
    ports:
      - '4200:4200'
    depends_on:
      - fr-admin-back

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - '8888:80'
    depends_on:
      - fr-admin-db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq

  mailer:
    build:
      context: ./quarkus/
      dockerfile: src/main/docker/Dockerfile.dev.jvm
    container_name: quarkus-mailer-dev
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
      - maildev

  maildev:
    image: maildev/maildev
    container_name: maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  fr-admin:
    driver: local
